-- Script to clean up existing data and re-seed with emojis
-- Run this script to update the database with the new emoji-enabled data

-- Delete existing data to avoid duplicates
DELETE FROM restaurant_cuisine_types;
DELETE FROM restaurant_restaurant_features;
DELETE FROM restaurant_dietary_options_junction;

-- Delete existing categories (be careful with this in production!)
DELETE FROM cuisine_types;
DELETE FROM restaurant_features;
DELETE FROM restaurant_dietary_options;

-- Seed data for cuisine types
INSERT INTO cuisine_types (name, description, icon) VALUES
('Italian', 'Italian cuisine and pasta dishes', '🍝'),
('Portuguese', 'Traditional Portuguese cuisine', '🇵🇹'),
('French', 'French fine dining and pastries', '🥐'),
('Japanese', 'Sushi, ramen, and Japanese dishes', '🍣'),
('Chinese', 'Chinese cuisine and dim sum', '🥢'),
('Indian', 'Indian curries and spices', '🌶️'),
('Mediterranean', 'Mediterranean healthy cuisine', '🥗'),
('Mexican', 'Tacos, burritos, and Mexican dishes', '🌮'),
('Thai', 'Thai curries and street food', '🌶️'),
('American', 'Burgers, BBQ, and American classics', '🍔'),
('Spanish', 'Tapas and Spanish cuisine', '🥘'),
('Greek', 'Greek dishes and Mediterranean flavors', '🏛️'),
('Turkish', 'Turkish kebabs and mezes', '🥙'),
('Brazilian', 'Brazilian churrasco and feijoada', '🥩'),
('Vietnamese', 'Pho and Vietnamese street food', '🍜'),
('Korean', 'Korean BBQ and kimchi dishes', '🇰🇷'),
('Lebanese', 'Lebanese mezze and grilled meats', '🥖'),
('Moroccan', 'Moroccan tagines and couscous', '🥘'),
('Peruvian', 'Peruvian ceviche and fusion cuisine', '🐟'),
('German', 'German sausages and beer halls', '🌭'),
('Russian', 'Russian borscht and dumplings', '🥟'),
('Ethiopian', 'Ethiopian injera and stews', '🥘'),
('Caribbean', 'Caribbean jerk and tropical flavors', '🏝️'),
('African', 'African traditional dishes', '🌍'),
('Fusion', 'Fusion and international cuisine', '🌍'),
('Vegetarian', 'Vegetarian-focused cuisine', '🥗'),
('Vegan', 'Vegan-exclusive cuisine', '🌱'),
('Seafood', 'Seafood and fish specialties', '🐟'),
('Steakhouse', 'Steak and grilled meats', '🥩'),
('Pizza', 'Pizza and Italian breads', '🍕'),
('Bakery', 'Bakery and pastries', '🥖'),
('Desserts', 'Desserts and sweets', '🍰'),
('Breakfast', 'Breakfast and brunch', '🥞'),
('Fast Food', 'Quick service and fast food', '🍟'),
('Fine Dining', 'Upscale fine dining', '🍽️'),
('Casual Dining', 'Casual restaurant experience', '🍴'),
('Street Food', 'Street food and food trucks', '🚚'),
('Home Cooking', 'Home-style and comfort food', '🏠'),
('Organic', 'Organic and healthy options', '🍎'),
('Gluten-free', 'Gluten-free specialized cuisine', '🌾'),
('Mediterrânea', 'Mediterrânea saudável', '🫒'),
('Oriental', 'Culinária oriental', '🥢'),
('Árabe', 'Comida árabe', '🫓'),
('Carnívora', 'Especializada em carnes', '🥩'),
('Pescetariana', 'Baseada em peixes e frutos do mar', '🐟'),
('Lacto-vegetariana', 'Vegetariana com laticínios', '🥛'),
('Ovo-vegetariana', 'Vegetariana com ovos', '🥚'),
('Crudívora', 'Alimentos crus e naturais', '🥕'),
('Frugívora', 'Baseada em frutas', '🍎'),
('Apimentada', 'Comida picante e temperada', '🌶️'),
('Doce', 'Sobremesas e doces', '🍭'),
('Salgada', 'Salgados e petiscos', '🧂'),
('Saudável', 'Alimentos saudáveis', '🥬'),
('Gourmet', 'Culinária gourmet', '🍷'),
('Tradicional', 'Comida tradicional', '🏺'),
('Contemporânea', 'Culinária contemporânea', '✨'),
('Fusão', 'Culinária de fusão', '🔀'),
('Orgânica', 'Alimentos orgânicos', '🌿');

-- Seed data for restaurant features
INSERT INTO restaurant_features (name, description, icon) VALUES
('Wi-Fi', 'Free Wi-Fi available', '📡'),
('Outdoor Seating', 'Terrace or outdoor seating area', '🌳'),
('Parking', 'On-site parking available', '🚗'),
('Air Conditioning', 'Climate controlled indoor seating', '❄️'),
('Reservations', 'Accepts reservations', '📅'),
('Delivery', 'Food delivery service', '🛵'),
('Takeout', 'Takeout/takeaway service', '🥡'),
('Vegetarian Options', 'Vegetarian menu options available', '🥗'),
('Vegan Options', 'Vegan menu options available', '🌱'),
('Gluten-free Options', 'Gluten-free menu options available', '🌾'),
('Pet Friendly', 'Pets allowed', '🐾'),
('Wheelchair Accessible', 'Accessible for wheelchair users', '♿'),
('Live Music', 'Live music entertainment', '🎵'),
('Happy Hour', 'Happy hour specials available', '🍸'),
('Kids Menu', 'Menu options for children', '👶'),
('Late Night', 'Open late hours', '🌙'),
('Group Dining', 'Suitable for large groups', '👥'),
('Private Room', 'Private dining room available', '🚪'),
('Catering', 'Catering services available', '🍽️'),
('Bar Service', 'Full bar service', '🍷'),
('Multibanco', 'ATM/Multibanco available', '🏧'),
('Cash Only', 'Accepts cash only', '💵'),
('Credit Cards', 'Accepts credit cards', '💳'),
('Contactless Payment', 'Contactless payment options', '📱'),
('Free Water', 'Free water available', '🚰'),
('High Speed Wi-Fi', 'High-speed internet connection', '🚀'),
('Business Lunch', 'Business lunch options', '💼'),
('Brunch', 'Brunch service available', '🍳'),
('Breakfast', 'Breakfast service available', '🥞'),
('Dessert Specialties', 'Specialized dessert menu', '🍰'),
('Wine List', 'Extensive wine selection', '🍷'),
('Craft Beer', 'Craft beer selection', '🍺'),
('Cocktails', 'Cocktail bar available', '🍸'),
('Coffee Specialties', 'Specialty coffee drinks', '☕'),
('Tea Selection', 'Variety of tea options', '🍵'),
('Gluten-free Menu', 'Dedicated gluten-free menu', '🌾'),
('Organic Options', 'Organic food options', '🍎'),
('Local Products', 'Uses local products', '📍'),
('Seasonal Menu', 'Seasonal menu changes', '🍂'),
('Chef Specials', 'Daily chef specials', '👨‍🍳'),
('Family Friendly', 'Adequado para famílias', '👨‍👩‍👧‍👦'),
('Romantic', 'Ambiente romântico', '💖'),
('Business', 'Para reuniões de negócios', '💼'),
('Casual', 'Ambiente descontraído', '👕'),
('Formal', 'Ambiente formal', '👔'),
('Rápido', 'Serviço rápido', '⚡'),
('Completo', 'Menu completo', '✅'),
('Básico', 'Menu básico', '📝'),
('Premium', 'Menu premium', '💎'),
('Econômico', 'Preços econômicos', '💰'),
('Gourmet', 'Culinária gourmet', '🍷'),
('Simples', 'Comida simples', '📝'),
('Elaborado', 'Comida elaborada', '🎨'),
('Criativo', 'Pratos criativos', '💡'),
('Clássico', 'Pratos clássicos', '📜'),
('Moderno', 'Culinária moderna', '✨'),
('Tradicional', 'Comida tradicional', '🏺'),
('Contemporâneo', 'Culinária contemporânea', '🎨'),
('Regional', 'Especialidades regionais', '🗺️'),
('Internacional', 'Culinária internacional', '🌐'),
('Sazonal', 'Pratos sazonais', '🍂'),
('Festivo', 'Para ocasiões especiais', '🎉');

-- Seed data for dietary options (limited to 50 practical options)
INSERT INTO restaurant_dietary_options (name, description, icon) VALUES
('Vegetariano', 'Opções vegetarianas disponíveis', '🥗'),
('Vegano', 'Opções vegan disponíveis', '🌱'),
('Sem Glúten', 'Opções sem glúten disponíveis', '🚫🌾'),
('Sem Lactose', 'Opções sem lactose disponíveis', '🚫🥛'),
('Sem Açúcar', 'Opções sem açúcar disponíveis', '🚫🍬'),
('Sem Sal', 'Opções sem sal disponíveis', '🚫🧂'),
('Sem Ovo', 'Opções sem ovo disponíveis', '🚫🥚'),
('Sem Soja', 'Opções sem soja disponíveis', '🚫🌱'),
('Sem Nozes', 'Opções sem nozes disponíveis', '🚫🥜'),
('Sem Marisco', 'Opções sem marisco disponíveis', '🚫🦐'),
('Sem Peixe', 'Opções sem peixe disponíveis', '🚫🐟'),
('Sem Carnes Vermelhas', 'Opções sem carnes vermelhas', '🚫🥩'),
('Sem Frango', 'Opções sem frango disponíveis', '🚫🍗'),
('Sem Porco', 'Opções sem porco disponíveis', '🚫🐗'),