-- Complete seed script for all filter data
-- Run this in your Supabase SQL editor to populate all filter categories

-- Seed data for restaurant features (40+ options)
INSERT INTO restaurant_features (name, description, icon) VALUES
('Wi-Fi', 'Free Wi-Fi available', '📡'),
('Outdoor Seating', 'Terrace or outdoor seating area', '🌳'),
('Parking', 'On-site parking available', '🚗'),
('Air Conditioning', 'Climate controlled indoor seating', '❄️'),
('Reservations', 'Accepts reservations', '📅'),
('Delivery', 'Food delivery service', '🛵'),
('Takeout', 'Takeout/takeaway service', '🥡'),
('Vegetarian Options', 'Vegetarian menu options available', '🥗'),
('Vegan Options', 'Vegan menu options available', '🌱'),
('Gluten-free Options', 'Gluten-free menu options available', '🌾'),
('Pet Friendly', 'Pets allowed', '🐾'),
('Wheelchair Accessible', 'Accessible for wheelchair users', '♿'),
('Live Music', 'Live music entertainment', '🎵'),
('Happy Hour', 'Happy hour specials available', '🍸'),
('Kids Menu', 'Menu options for children', '👶'),
('Late Night', 'Open late hours', '🌙'),
('Group Dining', 'Suitable for large groups', '👥'),
('Private Room', 'Private dining room available', '🚪'),
('Catering', 'Catering services available', '🍽️'),
('Bar Service', 'Full bar service', '🍷'),
('Multibanco', 'ATM/Multibanco available', '🏧'),
('Cash Only', 'Accepts cash only', '💵'),
('Credit Cards', 'Accepts credit cards', '💳'),
('Contactless Payment', 'Contactless payment options', '📱'),
('Free Water', 'Free water available', '🚰'),
('High Speed Wi-Fi', 'High-speed internet connection', '🚀'),
('Business Lunch', 'Business lunch options', '💼'),
('Brunch', 'Brunch service available', '🍳'),
('Breakfast', 'Breakfast service available', '🥞'),
('Dessert Specialties', 'Specialized dessert menu', '🍰'),
('Wine List', 'Extensive wine selection', '🍷'),
('Craft Beer', 'Craft beer selection', '🍺'),
('Cocktails', 'Cocktail bar available', '🍸'),
('Coffee Specialties', 'Specialty coffee drinks', '☕'),
('Tea Selection', 'Variety of tea options', '🍵'),
('Gluten-free Menu', 'Dedicated gluten-free menu', '🌾'),
('Organic Options', 'Organic food options', '🍎'),
('Local Products', 'Uses local products', '📍'),
('Seasonal Menu', 'Seasonal menu changes', '🍂'),
('Chef Specials', 'Daily chef specials', '👨‍🍳');

-- Seed data for dietary options (15+ options)
INSERT INTO restaurant_dietary_options (name, description, icon) VALUES
('Vegetarian', 'Restaurant offers vegetarian options', '🥗'),
('Vegan', 'Restaurant offers vegan options', '🌱'),
('Gluten-free', 'Restaurant offers gluten-free options', '🌾'),
('Dairy-free', 'Restaurant offers dairy-free options', '🥛'),
('Nut-free', 'Restaurant offers nut-free options', '🥜'),
('Halal', 'Restaurant serves halal food', '☪️'),
('Kosher', 'Restaurant serves kosher food', '✡️'),
('Organic', 'Restaurant uses organic ingredients', '🍎'),
('Low-carb', 'Restaurant offers low-carb options', '🥑'),
('Keto-friendly', 'Restaurant offers keto diet options', '🥓'),
('Paleo', 'Restaurant offers paleo diet options', '🥩'),
('Pescatarian', 'Restaurant offers pescatarian options', '🐟'),
('Lactose-free', 'Restaurant offers lactose-free options', '🧀'),
('Sugar-free', 'Restaurant offers sugar-free options', '🍭'),
('Whole30', 'Restaurant offers Whole30 compliant options', '🥕');

-- Seed data for cuisine types (40+ options)
INSERT INTO cuisine_types (name, description, icon) VALUES
('Italian', 'Italian cuisine and pasta dishes', '🍝'),
('Portuguese', 'Traditional Portuguese cuisine', '🇵🇹'),
('French', 'French fine dining and pastries', '🥐'),
('Japanese', 'Sushi, ramen, and Japanese dishes', '🍣'),
('Chinese', 'Chinese cuisine and dim sum', '🥢'),
('Indian', 'Indian curries and spices', '🌶️'),
('Mediterranean', 'Mediterranean healthy cuisine', '🥗'),
('Mexican', 'Tacos, burritos, and Mexican dishes', '🌮'),
('Thai', 'Thai curries and street food', '🌶️'),
('American', 'Burgers, BBQ, and American classics', '🍔'),
('Spanish', 'Tapas and Spanish cuisine', '🥘'),
('Greek', 'Greek dishes and Mediterranean flavors', '🏛️'),
('Turkish', 'Turkish kebabs and mezes', '🥙'),
('Brazilian', 'Brazilian churrasco and feijoada', '🥩'),
('Vietnamese', 'Pho and Vietnamese street food', '🍜'),
('Korean', 'Korean BBQ and kimchi dishes', '🇰🇷'),
('Lebanese', 'Lebanese mezze and grilled meats', '🥖'),
('Moroccan', 'Moroccan tagines and couscous', '🥘'),
('Peruvian', 'Peruvian ceviche and fusion cuisine', '🐟'),
('German', 'German sausages and beer halls', '🌭'),
('Russian', 'Russian borscht and dumplings', '🥟'),
('Ethiopian', 'Ethiopian injera and stews', '🥘'),
('Caribbean', 'Caribbean jerk and tropical flavors', '🏝️'),
('African', 'African traditional dishes', '🌍'),
('Fusion', 'Fusion and international cuisine', '🌍'),
('Vegetarian', 'Vegetarian-focused cuisine', '🥗'),
('Vegan', 'Vegan-exclusive cuisine', '🌱'),
('Seafood', 'Seafood and fish specialties', '🐟'),
('Steakhouse', 'Steak and grilled meats', '🥩'),
('Pizza', 'Pizza and Italian breads', '🍕'),
('Bakery', 'Bakery and pastries', '🥖'),
('Desserts', 'Desserts and sweets', '🍰'),
('Breakfast', 'Breakfast and brunch', '🥞'),
('Fast Food', 'Quick service and fast food', '🍟'),
('Fine Dining', 'Upscale fine dining', '🍽️'),
('Casual Dining', 'Casual restaurant experience', '🍴'),
('Street Food', 'Street food and food trucks', '🚚'),
('Home Cooking', 'Home-style and comfort food', '🏠'),
('Organic', 'Organic and healthy options', '🍎'),
('Gluten-free', 'Gluten-free specialized cuisine', '🌾');

-- Note: You may need to add sample data to the junction tables
-- to associate restaurants with their features, dietary options, and cuisine types
-- This would typically be done when creating or editing restaurants