-- Seed data for restaurant features
INSERT INTO restaurant_features (name, description, icon) VALUES
('Wi-Fi', 'Free Wi-Fi available', '📡'),
('Outdoor Seating', 'Terrace or outdoor seating area', '🌳'),
('Parking', 'On-site parking available', '🚗'),
('Air Conditioning', 'Climate controlled indoor seating', '❄️'),
('Reservations', 'Accepts reservations', '📅'),
('Delivery', 'Food delivery service', '🛵'),
('Takeout', 'Takeout/takeaway service', '🥡'),
('Vegetarian Options', 'Vegetarian menu options available', '🥗'),
('Vegan Options', 'Vegan menu options available', '🌱'),
('Gluten-free Options', 'Gluten-free menu options available', '🌾'),
('Pet Friendly', 'Pets allowed', '🐾'),
('Wheelchair Accessible', 'Accessible for wheelchair users', '♿'),
('Live Music', 'Live music entertainment', '🎵'),
('Happy Hour', 'Happy hour specials available', '🍸'),
('Kids Menu', 'Menu options for children', '👶'),
('Late Night', 'Open late hours', '🌙'),
('Group Dining', 'Suitable for large groups', '👥'),
('Private Room', 'Private dining room available', '🚪'),
('Catering', 'Catering services available', '🍽️'),
('Bar Service', 'Full bar service', '🍷'),
('Multibanco', 'ATM/Multibanco available', '🏧'),
('Cash Only', 'Accepts cash only', '💵'),
('Credit Cards', 'Accepts credit cards', '💳'),
('Contactless Payment', 'Contactless payment options', '📱'),
('Free Water', 'Free water available', '🚰'),
('High Speed Wi-Fi', 'High-speed internet connection', '🚀'),
('Business Lunch', 'Business lunch options', '💼'),
('Brunch', 'Brunch service available', '🍳'),
('Breakfast', 'Breakfast service available', '🥞'),
('Dessert Specialties', 'Specialized dessert menu', '🍰'),
('Wine List', 'Extensive wine selection', '🍷'),
('Craft Beer', 'Craft beer selection', '🍺'),
('Cocktails', 'Cocktail bar available', '🍸'),
('Coffee Specialties', 'Specialty coffee drinks', '☕'),
('Tea Selection', 'Variety of tea options', '🍵'),
('Gluten-free Menu', 'Dedicated gluten-free menu', '🌾'),
('Organic Options', 'Organic food options', '🍎'),
('Local Products', 'Uses local products', '📍'),
('Seasonal Menu', 'Seasonal menu changes', '🍂'),
('Chef Specials', 'Daily chef specials', '👨‍🍳'),
('Family Friendly', 'Adequado para famílias', '👨‍👩‍👧‍👦'),
('Romantic', 'Ambiente romântico', '💖'),
('Business', 'Para reuniões de negócios', '💼'),
('Casual', 'Ambiente descontraído', '👕'),
('Formal', 'Ambiente formal', '👔'),
('Casual', 'Ambiente informal', '👕'),
('Rápido', 'Serviço rápido', '⚡'),
('Completo', 'Menu completo', '✅'),
('Básico', 'Menu básico', '📝'),
('Premium', 'Menu premium', '💎'),
('Econômico', 'Preços econômicos', '💰'),
('Gourmet', 'Culinária gourmet', '🍷'),
('Simples', 'Comida simples', '📝'),
('Elaborado', 'Comida elaborada', '🎨'),
('Criativo', 'Pratos criativos', '💡'),
('Clássico', 'Pratos clássicos', '📜'),
('Moderno', 'Culinária moderna', '✨'),
('Tradicional', 'Comida tradicional', '🏺'),
('Contemporâneo', 'Culinária contemporânea', '🎨'),
('Regional', 'Especialidades regionais', '🗺️'),
('Internacional', 'Culinária internacional', '🌐'),
('Sazonal', 'Pratos sazonais', '🍂'),
('Festivo', 'Para ocasiões especiais', '🎉');

-- Seed data for dietary options (limited to 50 practical options)
INSERT INTO restaurant_dietary_options (name, description, icon) VALUES
('Vegetariano', 'Opções vegetarianas disponíveis', '🥗'),
('Vegano', 'Opções vegan disponíveis', '🌱'),
('Sem Glúten', 'Opções sem glúten disponíveis', '🚫🌾'),
('Sem Lactose', 'Opções sem lactose disponíveis', '🚫🥛'),
('Sem Açúcar', 'Opções sem açúcar disponíveis', '🚫🍬'),
('Sem Sal', 'Opções sem sal disponíveis', '🚫🧂'),
('Sem Ovo', 'Opções sem ovo disponíveis', '🚫🥚'),
('Sem Soja', 'Opções sem soja disponíveis', '🚫🌱'),
('Sem Nozes', 'Opções sem nozes disponíveis', '🚫🥜'),
('Sem Marisco', 'Opções sem marisco disponíveis', '🚫🦐'),
('Sem Peixe', 'Opções sem peixe disponíveis', '🚫🐟'),
('Sem Carnes Vermelhas', 'Opções sem carnes vermelhas', '🚫🥩'),
('Sem Frango', 'Opções sem frango disponíveis', '🚫🍗'),
('Sem Porco', 'Opções sem porco disponíveis', '🚫🐗'),
('Sem Alimentos Processados', 'Sem alimentos processados', '🚫🏭'),
('Sem Alimentos Fritos', 'Sem alimentos fritos', '🚫🍟'),
('Sem Alimentos Defumados', 'Sem alimentos defumados', '🚫🪵'),
('Sem Alimentos Picantes', 'Sem alimentos picantes', '🚫🌶️'),
('Sem Alimentos Amargos', 'Sem alimentos amargos', '🚫🍫'),
('Sem Alimentos Azedos', 'Sem alimentos azedos', '🚫🍋'),
('Sem Alimentos Doces', 'Sem alimentos doces', '🚫🍭'),
('Sem Alimentos Salgados', 'Sem alimentos salgados', '🚫🧂'),
('Sem Alimentos Gordurosos', 'Sem alimentos gordurosos', '🚫🥓'),
('Sem Alimentos Ricos em Carboidratos', 'Sem alimentos ricos em carboidratos', '🚫🍞'),
('Sem Alimentos Ricos em Proteínas', 'Sem alimentos ricos em proteínas', '🚫🥩'),
('Sem Alimentos Ricos em Gorduras', 'Sem alimentos ricos em gorduras', '🚫🥑'),
('Sem Alimentos Ricos em Açúcares', 'Sem alimentos ricos em açúcares', '🚫🍬'),
('Sem Alimentos Ricos em Sódio', 'Sem alimentos ricos em sódio', '🚫🧂'),
('Sem Alimentos Ricos em Fibras', 'Sem alimentos ricos em fibras', '🚫🌾'),
('Sem Alimentos Ricos em Vitaminas', 'Sem alimentos ricos em vitaminas', '🚫🍊'),
('Sem Alimentos Ricos em Minerais', 'Sem alimentos ricos em minerais', '🚫💎'),
('Sem Alimentos Ricos em Antioxidantes', 'Sem alimentos ricos em antioxidantes', '🚫🛡️'),
('Sem Alimentos Ricos em Ferro', 'Sem alimentos ricos em ferro', '🚫🧲'),
('Sem Alimentos Ricos em Cálcio', 'Sem alimentos ricos em cálcio', '🚫🥛'),
('Sem Alimentos Ricos em Magnésio', 'Sem alimentos ricos em magnésio', '🚫🌿'),
('Sem Alimentos Ricos em Potássio', 'Sem alimentos ricos em potássio', '🚫🍌'),
('Sem Alimentos Ricos em Vitamina C', 'Sem alimentos ricos em vitamina C', '🚫🍊'),
('Sem Alimentos Ricos em Vitamina D', 'Sem alimentos ricos em vitamina D', '🚫☀️'),
('Sem Alimentos Ricos em Vitamina E', 'Sem alimentos ricos em vitamina E', '🚫🥜'),
('Sem Alimentos Ricos em Vitamina K', 'Sem alimentos ricos em vitamina K', '🚫🥬'),
('Sem Alimentos Ricos em Vitamina B12', 'Sem alimentos ricos em vitamina B12', '🚫🥩'),
('Sem Alimentos Ricos em Vitamina B6', 'Sem alimentos ricos em vitamina B6', '🚫🐟'),
('Sem Alimentos Ricos em Vitamina B1', 'Sem alimentos ricos em vitamina B1', '🚫🌾'),
('Sem Alimentos Ricos em Vitamina B2', 'Sem alimentos ricos em vitamina B2', '🚫🥛'),
('Sem Alimentos Ricos em Vitamina B3', 'Sem alimentos ricos em vitamina B3', '🚫🍗'),
('Sem Alimentos Ricos em Vitamina B5', 'Sem alimentos ricos em vitamina B5', '🚫🥑'),
('Sem Alimentos Ricos em Vitamina B7', 'Sem alimentos ricos em vitamina B7', '🚫🥚'),
('Sem Alimentos Ricos em Vitamina B9', 'Sem alimentos ricos em vitamina B9', '🚫🥦'),
('Sem Alimentos Ricos em Colina', 'Sem alimentos ricos em colina', '🚫🥚'),
('Sem Alimentos Ricos em Inulina', 'Sem alimentos ricos em inulina', '🚫🌿'),
('Sem Alimentos Ricos em Probióticos', 'Sem alimentos ricos em probióticos', '🚫🦠'),
('Sem Alimentos Ricos em Prebióticos', 'Sem alimentos ricos em prebióticos', '🚫🌱'),
('Sem Alimentos Ricos em Enzimas', 'Sem alimentos ricos em enzimas', '🚫🔬'),
('Sem Alimentos Ricos em Aminoácidos', 'Sem alimentos ricos em aminoácidos', '🚫🧬'),
('Sem Alimentos Ricos em Ácidos Graxos', 'Sem alimentos ricos em ácidos graxos', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Ômega-3', 'Sem alimentos ricos em ômega-3', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Ômega-6', 'Sem alimentos ricos em ômega-6', '🚫🥜'),
('Sem Alimentos Ricos em Ácidos Graxos Ômega-9', 'Sem alimentos ricos em ômega-9', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Saturados', 'Sem alimentos ricos em gorduras saturadas', '🚫🥓'),
('Sem Alimentos Ricos em Ácidos Graxos Insaturados', 'Sem alimentos ricos em gorduras insaturadas', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Monoinsaturados', 'Sem alimentos ricos em gorduras monoinsaturadas', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Poli-insaturados', 'Sem alimentos ricos em gorduras poli-insaturadas', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Trans', 'Sem alimentos ricos em gorduras trans', '🚫🍔'),
('Sem Alimentos Ricos em Ácidos Graxos Cis', 'Sem alimentos ricos em gorduras cis', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Conjugados', 'Sem alimentos ricos em gorduras conjugadas', '🚫🥩'),
('Sem Alimentos Ricos em Ácidos Graxos Essenciais', 'Sem alimentos ricos em ácidos graxos essenciais', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Não Essenciais', 'Sem alimentos ricos em ácidos graxos não essenciais', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Saturados de Cadeia Curta', 'Sem alimentos ricos em gorduras saturadas de cadeia curta', '🚫🧈'),
('Sem Alimentos Ricos em Ácidos Graxos Saturados de Cadeia Média', 'Sem alimentos ricos em gorduras saturadas de cadeia média', '🚫🥥'),
('Sem Alimentos Ricos em Ácidos Graxos Saturados de Cadeia Longa', 'Sem alimentos ricos em gorduras saturadas de cadeia longa', '🚫🥩'),
('Sem Alimentos Ricos em Ácidos Graxos Insaturados de Cadeia Curta', 'Sem alimentos ricos em gorduras insaturadas de cadeia curta', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Insaturados de Cadeia Média', 'Sem alimentos ricos em gorduras insaturadas de cadeia média', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Insaturados de Cadeia Longa', 'Sem alimentos ricos em gorduras insaturadas de cadeia longa', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Monoinsaturados de Cadeia Curta', 'Sem alimentos ricos em gorduras monoinsaturadas de cadeia curta', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Monoinsaturados de Cadeia Média', 'Sem alimentos ricos em gorduras monoinsaturadas de cadeia média', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Monoinsaturados de Cadeia Longa', 'Sem alimentos ricos em gorduras monoinsaturadas de cadeia longa', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Poli-insaturados de Cadeia Curta', 'Sem alimentos ricos em gorduras poli-insaturadas de cadeia curta', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Poli-insaturados de Cadeia Média', 'Sem alimentos ricos em gorduras poli-insaturadas de cadeia média', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Poli-insaturados de Cadeia Longa', 'Sem alimentos ricos em gorduras poli-insaturadas de cadeia longa', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Trans de Cadeia Curta', 'Sem alimentos ricos em gorduras trans de cadeia curta', '🚫🍔'),
('Sem Alimentos Ricos em Ácidos Graxos Trans de Cadeia Média', 'Sem alimentos ricos em gorduras trans de cadeia média', '🚫🍔'),
('Sem Alimentos Ricos em Ácidos Graxos Trans de Cadeia Longa', 'Sem alimentos ricos em gorduras trans de cadeia longa', '🚫🍔'),
('Sem Alimentos Ricos em Ácidos Graxos Cis de Cadeia Curta', 'Sem alimentos ricos em gorduras cis de cadeia curta', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Cis de Cadeia Média', 'Sem alimentos ricos em gorduras cis de cadeia média', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Cis de Cadeia Longa', 'Sem alimentos ricos em gorduras cis de cadeia longa', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Conjugados de Cadeia Curta', 'Sem alimentos ricos em gorduras conjugadas de cadeia curta', '🚫🥩'),
('Sem Alimentos Ricos em Ácidos Graxos Conjugados de Cadeia Média', 'Sem alimentos ricos em gorduras conjugadas de cadeia média', '🚫🥩'),
('Sem Alimentos Ricos em Ácidos Graxos Conjugados de Cadeia Longa', 'Sem alimentos ricos em gorduras conjugadas de cadeia longa', '🚫🥩'),
('Sem Alimentos Ricos em Ácidos Graxos Essenciais de Cadeia Curta', 'Sem alimentos ricos em ácidos graxos essenciais de cadeia curta', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Essenciais de Cadeia Média', 'Sem alimentos ricos em ácidos graxos essenciais de cadeia média', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Essenciais de Cadeia Longa', 'Sem alimentos ricos em ácidos graxos essenciais de cadeia longa', '🚫🐟'),
('Sem Alimentos Ricos em Ácidos Graxos Não Essenciais de Cadeia Curta', 'Sem alimentos ricos em ácidos graxos não essenciais de cadeia curta', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Não Essenciais de Cadeia Média', 'Sem alimentos ricos em ácidos graxos não essenciais de cadeia média', '🚫🥑'),
('Sem Alimentos Ricos em Ácidos Graxos Não Essenciais de Cadeia Longa', 'Sem alimentos ricos em ácidos graxos não essenciais de cadeia longa', '🚫🐟');

-- Sample data for restaurant_cuisine_types (if needed)
-- INSERT INTO restaurant_cuisine_types (restaurant_id, cuisine_type_id) VALUES
-- ('restaurant-uuid-here', 'cuisine-uuid-here');

-- Sample data for restaurant_features_mapping (if needed)
-- INSERT INTO restaurant_restaurant_features (restaurant_id, feature_id) VALUES
-- ('restaurant-uuid-here', 'feature-uuid-here');

-- Sample data for restaurant_dietary_options_junction (if needed)
-- INSERT INTO restaurant_dietary_options_junction (restaurant_id, dietary_option_id) VALUES
-- ('restaurant-uuid-here', 'dietary-uuid-here');