-- Seed data for cuisine types
INSERT INTO cuisine_types (name, description, icon) VALUES
('Italian', 'Italian cuisine and pasta dishes', '🍝'),
('Portuguese', 'Traditional Portuguese cuisine', '🇵🇹'),
('French', 'French fine dining and pastries', '🥐'),
('Japanese', 'Sushi, ramen, and Japanese dishes', '🍣'),
('Chinese', 'Chinese cuisine and dim sum', '🥢'),
('Indian', 'Indian curries and spices', '🌶️'),
('Mediterranean', 'Mediterranean healthy cuisine', '🥗'),
('Mexican', 'Tacos, burritos, and Mexican dishes', '🌮'),
('Thai', 'Thai curries and street food', '🌶️'),
('American', 'Burgers, BBQ, and American classics', '🍔'),
('Spanish', 'Tapas and Spanish cuisine', '🥘'),
('Greek', 'Greek dishes and Mediterranean flavors', '🏛️'),
('Turkish', 'Turkish kebabs and mezes', '🥙'),
('Brazilian', 'Brazilian churrasco and feijoada', '🥩'),
('Vietnamese', 'Pho and Vietnamese street food', '🍜'),
('Korean', 'Korean BBQ and kimchi dishes', '🇰🇷'),
('Lebanese', 'Lebanese mezze and grilled meats', '🥖'),
('Moroccan', 'Moroccan tagines and couscous', '🥘'),
('Peruvian', 'Peruvian ceviche and fusion cuisine', '🐟'),
('German', 'German sausages and beer halls', '🌭'),
('Russian', 'Russian borscht and dumplings', '🥟'),
('Ethiopian', 'Ethiopian injera and stews', '🥘'),
('Caribbean', 'Caribbean jerk and tropical flavors', '🏝️'),
('African', 'African traditional dishes', '🌍'),
('Fusion', 'Fusion and international cuisine', '🌍'),
('Vegetarian', 'Vegetarian-focused cuisine', '🥗'),
('Vegan', 'Vegan-exclusive cuisine', '🌱'),
('Seafood', 'Seafood and fish specialties', '🐟'),
('Steakhouse', 'Steak and grilled meats', '🥩'),
('Pizza', 'Pizza and Italian breads', '🍕'),
('Bakery', 'Bakery and pastries', '🥖'),
('Desserts', 'Desserts and sweets', '🍰'),
('Breakfast', 'Breakfast and brunch', '🥞'),
('Fast Food', 'Quick service and fast food', '🍟'),
('Fine Dining', 'Upscale fine dining', '🍽️'),
('Casual Dining', 'Casual restaurant experience', '🍴'),
('Street Food', 'Street food and food trucks', '🚚'),
('Home Cooking', 'Home-style and comfort food', '🏠'),
('Organic', 'Organic and healthy options', '🍎'),
('Gluten-free', 'Gluten-free specialized cuisine', '🌾');