export type LanguageCode = 'pt' | 'en';

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
];

// PT is the source of truth (keys). EN overrides. Missing key => falls back to PT.
export const EN: Record<string, string> = {
  Restaurantes: 'Restaurants',
  Mapa: 'Map',
  Listas: 'Lists',
  'Pesquisar...': 'Search...',
  'Menu do usuário': 'User menu',
  'Meu Perfil': 'My Profile',
  Configurações: 'Settings',
  Refeições: 'Meals',
  'Criar restaurante': 'Create restaurant',
  'Roleta de Restaurantes': 'Restaurant Roulette',
  Sair: 'Sign out',
  Admin: 'Admin',
  // F1 core
  'Nenhum resultado encontrado': 'No results found',
  'Não encontramos nenhum restaurante que corresponda a "{q}".': 'No restaurant matches "{q}".',
  'Limpar pesquisa': 'Clear search',
  'Nenhum restaurante cadastrado': 'No restaurants yet',
  'Comece adicionando seu primeiro restaurante para criar sua coleção gastronômica.': 'Start by adding your first restaurant to create your collection.',
  'Adicionar Restaurante': 'Add Restaurant',
  'Cancelar': 'Cancel',
  'Salvando...': 'Saving...',
  'Pesquisar restaurantes, listas, utilizadores...': 'Search restaurants, lists, users...',
  "Abrir site": "Open website",
  "Ver menu": "View menu",
  "Descreva sua visita e mencione users com @": "Describe your visit and mention users with @",
  "Compartilhe sua experi\u00eancia (escreve @ para mencionar)": "Share your experience (type @ to mention)",
  "Valor Gasto": "Amount Spent",
  "Fotos da experiencia": "Experience photos",
  "Nenhuma avaliacao ainda": "No reviews yet",
  "Seja o primeiro a partilhar a sua experiencia!": "Be the first to share your experience!",
  "Fazer avaliacao": "Write a review",
  "Nenhuma imagem do menu": "No menu images",
  "ESC Fechar": "ESC Close",
  "Imagens anteriores": "Previous images",
  "Pr\u00f3ximas imagens": "Next images",
  "Fechar modal": "Close modal",
  "Imagem anterior": "Previous image",
  "Pr\u00f3xima imagem": "Next image",
  "Telefones para contato": "Contact phones",
  "A carregar...": "Loading...",
  "Nenhuma lista corresponde": "No matching lists",
  "Na lista": "In list",
  "Filtrar listas...": "Filter lists...",
  "por pessoa": "per person",
  "Agendar Refeicao": "Schedule Meal",
  "Fotos do Menu": "Menu photos",
  "Imagens do Menu": "Menu images",
  "Opcoes Dieteticas": "Dietary Options",
  "Sem categorias definidas": "No categories defined",
  "Nenhuma imagem dispon\u00edvel": "No image available",
  "Swipe arrastar": "Swipe to drag",
  "Arraste para navegar": "Drag to navigate",
  "Nenhuma imagem adicionada": "No images added",
  "Adicione imagens do restaurante para criar um carrossel atrativo": "Add restaurant images to create an attractive carousel",
  "Fazendo upload...": "Uploading...",
  "Erro no upload": "Upload error",
  "Tentar novamente": "Try again",
  "Nenhum link adicionado": "No links added",
  "Adicione links externos para menus do restaurante": "Add external links for restaurant menus",
  "Fa\u00e7a upload de imagens dos menus do restaurante": "Upload restaurant menu images",
  "Remover link": "Remove link",
  "Remover imagem": "Remove image",
  "Google Maps": "Google Maps",
  "Links do Menu": "Menu Links",
  "Informa\u00e7\u00f5es B\u00e1sicas": "Basic Information",
  "Nome": "Name",
  "Descri\u00e7\u00e3o": "Description",
  "Localiza\u00e7\u00e3o": "Location",
  "Categorias Culin\u00e1rias": "Cuisine Categories",
  "Op\u00e7\u00f5es Diet\u00e9ticas": "Dietary Options",
  "Caracter\u00edsticas": "Features",
  "Imagens": "Images",
  "Informa\u00e7\u00f5es Adicionais": "Additional Information",
  "Website": "Website",
  "Telefones": "Phones",
  "Avaliar Restaurante": "Review Restaurant",
  "Fazer primeira avaliacao": "Write first review",
  "Editar avaliacao": "Edit review",
  "Eliminar avaliacao": "Delete review",
  "Restaurante n\u00e3o encontrado": "Restaurant not found",
  "Restaurante nao encontrado": "Restaurant not found",
  "Nome da Lista *": "List Name *",
  "URL da Imagem de Capa": "Cover Image URL",
  "Ainda nao adicionaste restaurantes.": "You haven't added any restaurants yet.",
  "Informacoes Basicas": "Basic Information",
  "Ex: Melhores restaurantes italianos": "E.g. Best Italian restaurants",
  "Descreve o tema desta lista...": "Describe this list's theme...",
  "Visibilidade": "Visibility",
  "Adicionar Restaurantes": "Add Restaurants",
  "Pesquisar por nome...": "Search by name...",
  "Capa e Tags": "Cover & Tags",
  "https://exemplo.com/imagem.jpg": "https://example.com/image.jpg",
  "Adiciona tags (Enter para confirmar)": "Add tags (Enter to confirm)",
  "Restaurantes Selecionados": "Selected Restaurants",
  "Concluir": "Finish",
  "Nenhum restaurante corresponde aos filtros": "No restaurants match the filters",
  "Procurar restaurantes...": "Search restaurants...",
  "Remover restaurante": "Remove restaurant",
  "Nenhum utilizador encontrado": "No user found",
  "Pesquisar por nome ou codigo FL000001...": "Search by name or code FL000001...",
  "Remover colaborador": "Remove collaborator",
  "Adicionar comentario... escreve @ para mencionar": "Add comment... type @ to mention",
  "Guardar": "Save",
  "Editar comentario": "Edit comment",
  "Eliminar comentario": "Delete comment",
  "Pesquisar listas...": "Search lists...",
  "Preco medio": "Average price",
  "Aplicar filtros": "Apply filters",
  "Exportar localmente": "Export locally",
  "Download via API": "Download via API",
  "Rating medio": "Average rating",
  "Distribuicao de precos": "Price distribution",
  "Criar lista": "Create list",
  "Lista nao encontrada": "List not found",
  "Voltar as listas": "Back to lists",
  "Exportar Lista": "Export List",

  // F4 auth
  "Bem-vindo de volta": "Welcome back",
  "Continua a organizar as tuas experiencias gastronomicas": "Keep organizing your food experiences",
  "Email": "Email",
  "Endereco de email": "Email address",
  "Password": "Password",
  "Esqueceu a password?": "Forgot your password?",
  "Entrar": "Sign in",
  "Nao tem conta?": "Don't have an account?",
  "Crie uma gratuita": "Create one for free",
  "Entrar - FoodLister": "Sign in - FoodLister",
  "Criar Conta": "Create Account",
  "Junta-te a comunidade FoodLister": "Join the FoodLister community",
  "Password (min. 6 caracteres)": "Password (min. 6 characters)",
  "Confirmar Password": "Confirm Password",
  "Confirmar password": "Confirm password",
  "Ja tem conta?": "Already have an account?",
  "Faca login": "Log in",
  "Criar conta - FoodLister": "Create account - FoodLister",
  "Verifique o seu email e clique no link de confirmacao antes de fazer login.": "Check your email and click the confirmation link before logging in.",
  "Erro ao fazer login: {error}": "Error signing in: {error}",
  "Erro inesperado. Tente novamente.": "Unexpected error. Please try again.",
  "Tente novamente": "Try again",
  "As senhas nao coincidem": "Passwords do not match",
  "A password deve ter pelo menos 6 caracteres": "Password must be at least 6 characters",
  "Erro ao criar conta: {error}": "Error creating account: {error}",

  // F4 auth — reset/verify
  "Digite o seu email": "Enter your email",
  "Erro ao enviar codigo. Verifique se o email esta correto.": "Error sending the code. Check if the email is correct.",
  "Codigo de 6 digitos enviado para o seu email!": "A 6-digit code was sent to your email!",
  "Digite o codigo de 6 digitos": "Enter the 6-digit code",
  "Codigo invalido ou expirado.": "Invalid or expired code.",
  "Codigo verificado! Defina a sua nova password.": "Code verified! Set your new password.",
  "Erro ao verificar codigo.": "Error verifying code.",
  "Erro ao atualizar password.": "Error updating password.",
  "Password Atualizada!": "Password Updated!",
  "A sua password foi alterada com sucesso. A redirecionar...": "Your password was changed successfully. Redirecting...",
  "Recuperar Password": "Recover Password",
  "Introduza o seu email para receber um codigo de verificacao": "Enter your email to receive a verification code",
  "Enviar Codigo": "Send Code",
  "Verificar Codigo": "Verify Code",
  "Introduza o codigo de 6 digitos enviado para ": "Enter the 6-digit code sent to ",
  "Codigo": "Code",
  "Verificar": "Verify",
  "Nova Password": "New Password",
  "Defina a sua nova password": "Set your new password",
  "Nova password (min. 6 caracteres)": "New password (min. 6 characters)",
  "Atualizar Password": "Update Password",
  "Voltar ao login": "Back to login",
  "Repor palavra-passe - FoodLister": "Reset password - FoodLister",
  "Token de verificação inválido ou em falta.": "Invalid or missing verification token.",
  "Falha ao verificar o email. O token pode ter expirado.": "Failed to verify the email. The token may have expired.",
  "Verificação de Email": "Email Verification",
  "A verificar o seu email...": "Verifying your email...",
  "Email verificado com sucesso!": "Email verified successfully!",
  "A redirecionar...": "Redirecting...",
  "Falha na verificação": "Verification failed",
  "Ir para Login": "Go to Login",
  "Página Inicial": "Home",
  "Verificar email - FoodLister": "Verify email - FoodLister",
  "Email Verificado!": "Email Verified!",
  "O seu email foi verificado com sucesso. Agora tem acesso a todas as funcionalidades do FoodLister.": "Your email was verified successfully. You now have access to all FoodLister features.",
  "Fazer Login": "Log in",
  "Ir para Página Inicial": "Go to Home",
  "Email verificado - FoodLister": "Email verified - FoodLister",


  // F4 settings
  "Perfil agora e privado!": "Profile is now private!",
  "Perfil agora e publico!": "Profile is now public!",
  "Erro ao atualizar privacidade": "Error updating privacy",
  "Imagem atualizada!": "Image updated!",
  "Erro ao carregar imagem": "Error loading image",
  "Nome de exibicao e obrigatorio": "Display name is required",
  "Formato de URL invalido": "Invalid URL format",
  "A biografia deve ter no maximo 500 caracteres": "Bio must be at most 500 characters",
  "Por favor, corrija os erros": "Please fix the errors",
  "Erro ao salvar perfil": "Error saving profile",
  "Carregando perfil...": "Loading profile...",
  "Erro ao carregar perfil": "Error loading profile",
  "Tentar Novamente": "Try Again",
  "Perfil nao encontrado": "Profile not found",
  "Celebração": "Celebration",
  "Perfil Atualizado!": "Profile Updated!",
  "As suas informacoes foram salvas com sucesso.": "Your information was saved successfully.",
  "Configuracoes": "Settings",
  "Gerencia as suas informacoes pessoais e privacidade": "Manage your personal information and privacy",
  "Perfil": "Profile",
  "Privacidade": "Privacy",
  "Estatisticas": "Statistics",
  "Foto de Perfil": "Profile Picture",
  "Clique no icone para alterar a foto": "Click the icon to change your photo",
  "Informacoes Pessoais": "Personal Information",
  "Nome de Exibicao *": "Display Name *",
  "O seu nome": "Your name",
  "O email nao pode ser alterado": "Email cannot be changed",
  "Telefone": "Phone",
  "Localizacao": "Location",
  "Porto, Portugal": "Porto, Portugal",
  "Bio": "Bio",
  "Conte um pouco sobre si...": "Tell us a little about yourself...",
  "Maximo 500 caracteres": "Maximum 500 characters",
  "Privacidade do Perfil": "Profile Privacy",
  "Escolha quem pode ver o seu perfil.": "Choose who can see your profile.",
  "Perfil Publico": "Public Profile",
  "Qualquer pessoa pode encontrar e ver o seu perfil": "Anyone can find and view your profile",
  "Perfil Privado": "Private Profile",
  "Apenas voce pode ver o seu perfil": "Only you can view your profile",
  "Ver Perfil Publico": "View Public Profile",
  "Como outros utilizadores veem o seu perfil": "How other users see your profile",
  "O seu impacto na comunidade FoodLister.": "Your impact on the FoodLister community.",
  "Reviews": "Reviews",
  "Adicionados": "Added",
  "Anterior": "Previous",
  "Proximo": "Next",
  "A salvar...": "Saving...",
  "Salvar Alteracoes": "Save Changes",
  "Definições - FoodLister": "Settings - FoodLister",
  "{current} de 3": "{current} of 3",


  // F4 notifications
  "Preferencias de Notificacoes": "Notification Preferences",
  "Escolhe que tipo de notificacoes recebes e como as recebes": "Choose what type of notifications you receive and how",
  "A carregar preferencias...": "Loading preferences...",
  "Metodo de Entrega": "Delivery Method",
  "Notificacoes por Email": "Email Notifications",
  "Recebe notificacoes importantes no teu email": "Receive important notifications in your email",
  "Notificacoes Push": "Push Notifications",
  "Recebe notificacoes no navegador em tempo real": "Receive real-time notifications in your browser",
  "Resumo Semanal": "Weekly Digest",
  "Recebe um resumo semanal da atividade nas tuas listas": "Receive a weekly summary of activity on your lists",
  "Tipos de Notificacao": "Notification Types",
  "Convites para Refeicoes": "Meal Invitations",
  "Quando te convidam para uma refeicao em grupo": "When you're invited to a group meal",
  "Atualizacoes de Colaboradores": "Collaborator Updates",
  "Quando alguem colabora nas tuas listas": "When someone collaborates on your lists",
  "Atividade em Listas": "List Activity",
  "Mudancas e comentarios nas tuas listas": "Changes and comments on your lists",
  "Atualizacoes do Sistema": "System Updates",
  "Novidades, manutencao e avisos importantes": "News, maintenance and important notices",
  "Nota:": "Note:",
  "As notificacoes push requerem que o teu navegador tenha permissoes de notificacao ativadas.": "Push notifications require browser notification permissions to be enabled.",
  "Definições · Notificações - FoodLister": "Settings · Notifications - FoodLister",


  // F4 profile & meals
  "FoodLister - Perfil": "FoodLister - Profile",
  "Link copiado!": "Link copied!",
  "Ve o perfil de {name}": "See {name}'s profile",
  "A seguir {name} agora!": "Now following {name}!",
  "Deixaste de seguir.": "Unfollowed.",
  "Erro ao alterar seguimento": "Error changing follow status",
  "Explorar Restaurantes": "Explore Restaurants",
  "Ultimas Reviews": "Latest Reviews",
  "Restaurante": "Restaurant",
  "Nenhuma review encontrada.": "No reviews found.",
  "Refeições - FoodLister": "Meals - FoodLister",
  "Precisa de estar autenticado para ver as suas refeicoes.": "You need to be authenticated to view your meals.",
  "Refeicoes": "Meals",
  "Gere as tuas refeicoes agendadas": "Manage your scheduled meals",
  "Nenhuma refeicao agendada": "No scheduled meals",
  "Agenda uma refeicao a partir de qualquer restaurante.": "Schedule a meal from any restaurant.",


  // F4 meal detail
  "Presença confirmada!": "Attendance confirmed!",
  "Erro ao confirmar presença": "Error confirming attendance",
  "Presença recusada": "Attendance declined",
  "Erro ao recusar presença": "Error declining attendance",
  "Refeição atualizada com sucesso!": "Meal updated successfully!",
  "Erro ao atualizar refeição": "Error updating meal",
  "Refeição eliminada com sucesso!": "Meal deleted successfully!",
  "Erro ao eliminar refeição": "Error deleting meal",
  "FoodLister - Refeição": "FoodLister - Meal",
  "A carregar detalhes da refeição...": "Loading meal details...",
  "Refeição não encontrada": "Meal not found",
  "A refeição que procuras não existe ou foi removida.": "The meal you're looking for doesn't exist or was removed.",
  "Voltar ao perfil": "Back to profile",
  "Voltar": "Back",
  "Organizador": "Organizer",
  "Editar refeição": "Edit meal",
  "Eliminar refeição": "Delete meal",
  "Data": "Date",
  "Hora": "Time",
  "Duração": "Duration",
  "{n} minutos": "{n} minutes",
  "Utilizador": "User",
  "Participantes ({n})": "Participants ({n})",
  "Ações": "Actions",
  "Download .ics (Calendário)": "Download .ics (Calendar)",
  "Adicionar ao Google Calendar": "Add to Google Calendar",
  "A confirmar...": "Confirming...",
  "Aceite ✓": "Accepted ✓",
  "Confirmar Presença": "Confirm Attendance",
  "A recusar...": "Declining...",
  "Recusado ✓": "Declined ✓",
  "Recusar": "Decline",
  "Ver página do restaurante →": "View restaurant page →",
  "Editar Refeição": "Edit Meal",
  "Tipo de refeição": "Meal type",
  "Pequeno Almoço": "Breakfast",
  "Almoço": "Lunch",
  "Lanche": "Snack",
  "Jantar": "Dinner",
  "Ceia": "Supper",
  "Duração (minutos)": "Duration (minutes)",
  "30 minutos": "30 minutes",
  "1 hora": "1 hour",
  "1.5 horas": "1.5 hours",
  "2 horas": "2 hours",
  "3 horas": "3 hours",
  "4 horas": "4 hours",
  "A guardar...": "Saving...",
  "Guardar alterações": "Save changes",
  "Confirmar eliminação": "Confirm deletion",
  "Eliminar refeição?": "Delete meal?",
  "Esta ação irá eliminar a refeição e todas as participações associadas. Esta ação não pode ser desfeita.": "This will delete the meal and all associated participations. This action cannot be undone.",
  "A eliminar...": "Deleting...",
  "Eliminar": "Delete",
  "Aceite": "Accepted",
  "Recusado": "Declined",
  "Pendente": "Pending",


  // F4 auth components
  "Email de verificação enviado! Verifique sua caixa de entrada.": "Verification email sent! Check your inbox.",
  "Não recebeu o email de verificação? Insira seu email abaixo para reenviar.": "Didn't receive the verification email? Enter your email below to resend.",
  "Enviando...": "Sending...",
  "Reenviar Email de Verificação": "Resend Verification Email",
  "Carregando status de verificação...": "Loading verification status...",
  "Status de verificação indisponível.": "Verification status unavailable.",
  "Email Verificado": "Email Verified",
  "Email Não Verificado": "Not Verified",
  "Verificado em: {date}": "Verified on: {date}",
  "Por favor, verifique seu email para ativar todas as funcionalidades.": "Please verify your email to activate all features.",


  // F7 toasts
  "Sessão expirada. Por favor, faça login novamente.": "Session expired. Please log in again.",
  "Login realizado com sucesso!": "Logged in successfully!",
  "Erro ao fazer login. Verifique suas credenciais.": "Login error. Check your credentials.",
  "Cadastro realizado com sucesso!": "Account created successfully!",
  "Erro ao criar conta. Tente novamente.": "Error creating account. Try again.",
  "Email de recuperação enviado!": "Recovery email sent!",
  "Erro ao enviar email de recuperação.": "Error sending recovery email.",
  "Preferências atualizadas com sucesso": "Preferences updated successfully",
  "Erro ao carregar refeições agendadas": "Error loading scheduled meals",
  "Refeição agendada com sucesso!": "Meal scheduled successfully!",
  "Participantes adicionados com sucesso!": "Participants added successfully!",
  "Dados atualizados!": "Data updated!",
  "Lista atualizada com sucesso!": "List updated successfully!",
  "Lista criada com sucesso!": "List created successfully!",
  "A janela popup foi bloqueada pelo navegador. Por favor, permita popups para este site e tente novamente.": "The popup window was blocked by your browser. Please allow popups for this site and try again.",
  "Evento criado com sucesso no Google Calendar!": "Event created successfully in Google Calendar!",
  "Link do perfil copiado!": "Profile link copied!",
  "Erro ao copiar link": "Error copying link",
  "Função de alteração de privacidade não configurada": "Privacy toggle function not configured.",
  "Erro ao atualizar privacidade do perfil": "Error updating profile privacy",
  "Função de upload de imagem não configurada": "Image upload function not configured.",
  "Imagem atualizada com sucesso!": "Image updated successfully!",
  "Erro ao atualizar imagem de perfil": "Error updating profile image",
  "Por favor, corrija os erros no formulário": "Please fix the errors in the form",
  "Função de salvamento não configurada": "Save function not configured.",
  "Perfil atualizado com sucesso!": "Profile updated successfully!",
  "Erro ao carregar restaurante": "Error loading restaurant",
  "Restaurante atualizado com sucesso!": "Restaurant updated successfully!",
  "Restaurante criado com sucesso!": "Restaurant created successfully!",
  "Erro de permissão. Verifique suas configurações de acesso.": "Permission error. Check your access settings.",
  "Erro ao salvar restaurante. Tente novamente.": "Error saving restaurant. Try again.",
  "Campanha criada com sucesso": "Campaign created successfully",
  "Post criado com sucesso": "Post created successfully",
  "Workflow criado com sucesso": "Workflow created successfully",
  "Subscrição será cancelada no final do período": "Subscription will be canceled at the end of the period",
  "Subscrição cancelada": "Subscription canceled",
  "Partilhado com sucesso!": "Shared successfully!",
  "Link copiado para a área de transferência!": "Link copied to clipboard!",
  "Erro ao copiar o link": "Error copying the link",
  "Seleciona um restaurante para gerar conteúdo com IA": "Select a restaurant to generate AI content",
  "Escreve o conteúdo ou gera com IA": "Write the content or generate with AI",
  "Restaurante removido!": "Restaurant removed!",
  "Erro ao remover restaurante": "Error removing restaurant",
  "Lista duplicada!": "List duplicated!",
  "Erro ao duplicar": "Error duplicating",
  "Lista eliminada!": "List deleted!",
  "Erro ao eliminar": "Error deleting",
  "Inicia sessão para subscrever": "Log in to subscribe",
  "Avaliação enviada com sucesso!": "Review submitted successfully!",
  "Restaurante eliminado com sucesso!": "Restaurant deleted successfully!",
  "Não foi possível eliminar o restaurante.": "Could not delete the restaurant.",
  "Erro ao eliminar restaurante. Tente novamente.": "Error deleting restaurant. Try again.",
  "Avaliação eliminada com sucesso!": "Review deleted successfully!",
  "Erro ao eliminar avaliação. Tente novamente.": "Error deleting review. Try again.",
  "Precisa de estar autenticado para criar listas.": "You need to be authenticated to create lists.",
  "Precisa de estar autenticado para criar uma lista.": "You need to be authenticated to create a list.",
  "Você precisa estar logado para criar restaurantes.": "You need to be logged in to create restaurants.",
  "Precisa de estar autenticado para editar listas.": "You need to be authenticated to edit lists.",
  "Precisa de estar autenticado para editar uma lista.": "You need to be authenticated to edit a list.",
  "Você precisa estar logado para editar restaurantes.": "You need to be logged in to edit restaurants.",
  "Utilizador já é colaborador": "User is already a collaborator",
  "Pesquisa e seleciona um utilizador": "Search and select a user",
  "Colaborador adicionado com sucesso!": "Collaborator added successfully!",
  "Erro ao adicionar colaborador": "Error adding collaborator",
  "Colaborador removido com sucesso!": "Collaborator removed successfully!",
  "Erro ao remover colaborador": "Error removing collaborator",
  "Comentario adicionado!": "Comment added!",
  "Erro ao adicionar comentario": "Error adding comment",
  "Comentario eliminado!": "Comment deleted!",
  "Erro ao eliminar comentario": "Error deleting comment",
  "Comentario editado!": "Comment edited!",
  "Erro ao editar comentario": "Error editing comment",
  "Link do restaurante copiado!": "Restaurant link copied!",
  "Erro ao compartilhar restaurante": "Error sharing restaurant",
  "Erro ao eliminar o restaurante. Tente novamente.": "Error deleting the restaurant. Try again.",
  "Link da avaliação copiado!": "Review link copied!",
  "Erro ao compartilhar avaliação": "Error sharing review",
  "Localização não disponível para este restaurante.": "Location not available for this restaurant.",
  "Erro ao carregar listas": "Error loading lists",
  "Adicionado a lista": "Added to list",
  "Ja esta nesta lista": "Already in this list",
  "Erro ao adicionar a lista": "Error adding to list",
  "Erro ao eliminar avaliacao. Tente novamente.": "Error deleting review. Try again.",
  "Erro ao eliminar avaliacao.": "Error deleting review.",
  "Refeicao agendada com sucesso!": "Meal scheduled successfully!",
  "Todos os filtros salvos foram excluídos!": "All saved filters were cleared!",
  "Histórico de roletas limpo!": "Roulette history cleared!",
  "Erro ao eliminar lista": "Error deleting list",
  "Profile updated successfully!": "Profile updated successfully!",
  "Image uploaded successfully!": "Image uploaded successfully!",
};
